### ISSUE TITLE
Checkbox selection malfunctioning on project details for Cash section.

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportHub#10]
![2017-10-27_11-35-01](https://user-images.githubusercontent.com/29349472/32124912-f15bb7c8-bb7e-11e7-91a6-a26a8cb67f8d.gif)

There is scope value clash on checkboxes, both have 'health', worked when changed e.g mpc_purpose_type_id to 'health_services', not taking into consideration dependencies.

https://github.com/pfitzpaddy/ngm-reportHub/blob/474076cfe4591806f054b9ccf521e1d33020a82d/app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js#L80

https://github.com/pfitzpaddy/ngm-reportHub/blob/b3b4e693b45ce212416dfd543287ad199be1df1c/app/scripts/modules/cluster/views/forms/details/details.html#L211

https://github.com/pfitzpaddy/ngm-reportHub/blob/b3b4e693b45ce212416dfd543287ad199be1df1c/app/scripts/modules/cluster/views/forms/details/details.html#L230

**Comment by pfitzpaddy** [comment]
Thanks a good find, cheers

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD
