### ISSUE TITLE
Bugfix: ET ESNFI - HHs are dropdown, not numeric when ET, ESNFI and CASH/VOUCHER activitiy

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportHub#121]
Looks to be displaying attributes for the AFG cash form

![et esnfi cash_voucher_bug](https://user-images.githubusercontent.com/1784705/50224469-a136c680-03bb-11e9-8495-288d1988ee82.png)

**Comment by drfaustusfade** [comment]
hotfix: https://github.com/pfitzpaddy/ngm-reportHub/pull/122

**Comment by pfitzpaddy** [comment]
Merged
