### ISSUE TITLE
Activity Selection MHNT

### ISSUE THREAD

**Issue by opapadak** [pfitzpaddy/ngm-reportHub#56]
Dear all,
Most of the partners in the Health Cluster are doing activities in Mobile Health and Nutrition Team,
having a lot of activities to select when displaying a project. Would it be possible to have a button (in the way "Add training" or "Add beneficiaries" have from the report part) that when clicked, display all targets from MHNT? The list of it is included in the attached file, filtered by MHNT = "yes"
[Activities_MHNT.xlsx](https://github.com/pfitzpaddy/ngm-reportHub/files/1747606/Activities_MHNT.xlsx)

It is a just a suggestion

**Comment by pfitzpaddy** [comment]
Thats an interesting concept that could be useful - not just for MHNTs. Timur is back soon we will follow up on his return.
