### ISSUE TITLE
Activities update in ReportHub

### ISSUE THREAD

**Issue by opapadak** [pfitzpaddy/ngm-reportHub#64]
Dear all,
after some comment with partners, would it be possible to add the following activities to the health cluster in Ethiopia ?
Under Supply Logistics:
Add MCH supply 
Under Mother and Child Health Care
Add MCH Ostetric Referral  (pregnant women are referred)

In health, for Vaccination (TT) we would need to be able to select men and women (for all other vaccination it is ok with only boys and girls but for TT, women and men are targeted)

For nutrition cluster, 
add Gross monitoring nutrition under nutrition program

Finally could you add HSSS in the organization list?

thanks in advance

**Comment by drfaustusfade** [comment]
vaccination_tt https://github.com/pfitzpaddy/ngm-reportHub/pull/66

**Comment by drfaustusfade** [comment]
what is HSSS full name? ane org type?

**Comment by opapadak** [comment]
Sorry Let's forget about HSSS. 
One other asking would be to add Health Extension Worker to the list of units

**Comment by drfaustusfade** [comment]
added to pull request

**Comment by drfaustusfade** [comment]
activities updated
