### ISSUE TITLE
different access to the system

### ISSUE THREAD

**Issue by opapadak** [pfitzpaddy/ngm-reportHub#65]
Dear all,
I would like to know what are the different access to reporthub.
Our colleague Beatrice bmuraguri@immap.org who is the official cluster IMO does not have an access to check partners data (she is registered as a who member)

Also, with patrick's "Who-ethiopia" account, we can access partner's project and i can check and edit the reports but here is what i get for the project details 
![image](https://user-images.githubusercontent.com/4193028/37148189-92f011a2-22da-11e8-91e1-c715be354445.png)
What are the permissions for each authorization level?

Thanks!
Olivier

**Comment by drfaustusfade** [comment]
there is user, admin, and superadmin user types
user - organization
admin - cluster level
superadmin - country level

checked in prod and test project details worked for test users
is bmuraguri@immap.org  registered, cause there is no such user?

**Comment by opapadak** [comment]
Hi, she now has one account, username should be HealthCluster with email bmuraguri@immap.org
We would like for her to have admin level for the health cluster 
Thanks!

**Comment by drfaustusfade** [comment]
updated
