### ISSUE TITLE
Updating donors

### ISSUE THREAD

**Issue by opapadak** [pfitzpaddy/ngm-reportHub#72]
Dear all,
I update the donor of some of the projects, but it seems the [export link](http://reporthub.immap.org/api/cluster/indicator?adminRpcode=afro&admin0pcode=et&admin1pcode=all&admin2pcode=all&cluster_id=all&organization_tag=all&beneficiaries%5B%5D=all&start_date=2017-01-01&end_date=2018-12-31&csv=true&indicator=beneficiaries&report=all_beneficiary_data&ocha=true)  is not updating it 

project_id is 59faf61fdf5edb7a6c4ca995 (organization is MCMDO, it's their only project) and i removed ocha from (EHF, OCHA) in the user interface.
Same thing with project_id 5a8d76bf25d353777c6f72d2

Thanks in advance!

**Comment by pfitzpaddy** [comment]
Looks like this is an issue where the project is updated but then the beneficiaries collection is not. Could be a tricky one and limited by the implementation of the system.

**Comment by opapadak** [comment]
Does that mean all project details could not be changed once reporting begin?

**Comment by pfitzpaddy** [comment]
Of course they can, just need to take a look at whats going on here since the changes need to be updated across a few tables. This is happening correctly with all the other attributes, not sure why donor is not updated.

**Comment by drfaustusfade** [comment]
yes, beneficiaries collection is not updated, so that only new reported rows will contain change or re-saved reports. Business case if we update or not all project beneficiary data on project update.

**Comment by drfaustusfade** [comment]
[pull request](https://github.com/pfitzpaddy/ngm-reportEngine/pull/31) amends project update function to update beneficiaries collection for project_donor and project_title fields, others required fields to update can be added if needed

**Comment by opapadak** [comment]
Thanks!
I would have think about the project_budget, but actually it is not include for now in the export. 
@Patrick, Is it data to sensible to use?
If not I don't think we need other fields.

**Comment by pfitzpaddy** [comment]
Ok thanks guys, this is now updated. Note that Project Dates and Target Locations are critical to the reporting so these are updated by default when updated in PROJECT DETAILS. I will close the issue but if we need more data to be correctly updated we can include it.

**Comment by pfitzpaddy** [comment]
By the way, for the details you require @opapadak to be updated in the beneficiaries you will need to go and Save the project again and then they will be updated in the beneficiaries
