### ISSUE TITLE
Nutrition Landing Page Layout

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportHub#83]
Would it be an idea to have the Kobo form and dashboard on the same card, in much the same way as the Monitoring Assessment in Ethiopia?

**Ethiopia**
- Sample link http://reporthub.immap.org/desk/#/who/ethiopia
<img width="321" alt="monitoring" src="https://user-images.githubusercontent.com/1784705/38676814-e23cdde4-3e64-11e8-9317-9f64d40e1324.png">

I assume that the ADMIN is only visible to USER ROLE Admin. In that case the first 2 cards could be style="col s12 m6" when USER ROLE is USER and then style="col s12 m4" when USER ROLE is ADMIN.

If this is not relevant or if this is not a good idea then please just close the issue! Thanks

**Comment by drfaustusfade** [comment]
Yes, the plan is to have it like this, for standardize look of feature,  for now it's on pilot showcase
